[project]
name = "project-video-dubbeb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deep-translator>=1.11.4",
    "faster-whisper>=1.2.1",
    "ffmpeg-python>=0.2.0",
    "moviepy>=2.2.1",
    "openai>=2.14.0",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "numpy<2.4",
    "librosa>=0.10.0",
    "scipy>=1.10.0",
    "torch>=2.0.0",
    "torchaudio>=2.0.0",
    "transformers",
    "edge-tts>=7.2.7",
    "customtkinter>=5.2.2",
    "packaging",
    "pillow",
    "demucs",
    "f5-tts-th",
    "soundfile",
    "psutil",
    "gputil",
    "torchcodec",
    "sentencepiece",
    "protobuf",
    "deepface",
    "opencv-python",
    "mediapipe",
    "tf-keras",
]

[[tool.uv.index]]
name = "pytorch-nightly"
url = "https://download.pytorch.org/whl/nightly/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-nightly" }
torchaudio = { index = "pytorch-nightly" }
